<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/ml_python.png' width=600/></center>

<img src = "https://github.com/Jangrae/img/blob/master/mobile2.png?raw=true" width=800 align="left"/>

# 실습 내용

- Random Search로 KNN 알고리즘 모델을 튜닝합니다.

# 1.환경 준비

- 기본 라이브러리와 대상 데이터를 가져와 이후 과정을 준비합니다.

In [1]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings(action='ignore')
%config InlineBackend.figure_format='retina'

In [2]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/jangrae/csv/master/mobile.csv'
data = pd.read_csv(path)

# 2.데이터 이해

- 분석할 데이터를 충분히 이해할 수 있도록 다양한 탐색 과정을 수행합니다.

In [3]:
# 상위 몇 개 행 확인
data.head()

,id,COLLEGE,INCOME,OVERAGE,LEFTOVER,HOUSE,HANDSET_PRICE,OVER_15MINS_CALLS_PER_MONTH,AVERAGE_CALL_DURATION,REPORTED_SATISFACTION,REPORTED_USAGE_LEVEL,CONSIDERING_CHANGE_OF_PLAN,CHURN
0,1,0,31953,0,6,313378,161,0,4,unsat,little,no,0
1,2,1,36147,0,13,800586,244,0,6,unsat,little,considering,0
2,3,1,27273,230,0,305049,201,16,15,unsat,very_little,perhaps,0
3,4,0,120070,38,33,788235,780,3,2,unsat,very_high,considering,1
4,5,1,29215,208,85,224784,241,21,1,very_unsat,little,never_thought,0

In [4]:
# 기술통계 확인
data.describe()

,id,COLLEGE,INCOME,OVERAGE,LEFTOVER,HOUSE,HANDSET_PRICE,OVER_15MINS_CALLS_PER_MONTH,AVERAGE_CALL_DURATION,CHURN
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,10000.500000,0.502400,80281.447750,85.979550,23.898650,493155.264250,389.615100,8.000700,6.002250,0.492600
std,5773.647028,0.500007,41680.586319,85.992324,26.816645,252407.884692,213.820682,8.925418,4.402558,0.499958
min,1.000000,0.000000,20007.000000,-2.000000,0.000000,150002.000000,130.000000,0.000000,1.000000,0.000000
25%,5000.750000,0.000000,42217.000000,0.000000,0.000000,263714.250000,219.000000,1.000000,2.000000,0.000000
50%,10000.500000,1.000000,75366.500000,59.000000,14.000000,452259.500000,326.000000,4.000000,5.000000,0.000000
75%,15000.250000,1.000000,115881.750000,179.000000,41.000000,702378.000000,533.250000,15.000000,10.000000,1.000000
max,20000.000000,1.000000,159983.000000,335.000000,89.000000,999996.000000,899.000000,29.000000,15.000000,1.000000

# 3.데이터 준비

- 전처리 과정을 통해 머신러닝 알고리즘에 사용할 수 있는 형태의 데이터를 준비합니다.

**1) 변수 제거**

In [5]:
# 제거 대상: id
drop_col='id'

# 변수 제거
data.drop(drop_col, axis=1, inplace=True)

# 확인
data

,COLLEGE,INCOME,OVERAGE,LEFTOVER,HOUSE,HANDSET_PRICE,OVER_15MINS_CALLS_PER_MONTH,AVERAGE_CALL_DURATION,REPORTED_SATISFACTION,REPORTED_USAGE_LEVEL,CONSIDERING_CHANGE_OF_PLAN,CHURN
0,0,31953,0,6,313378,161,0,4,unsat,little,no,0
1,1,36147,0,13,800586,244,0,6,unsat,little,considering,0
2,1,27273,230,0,305049,201,16,15,unsat,very_little,perhaps,0
3,0,120070,38,33,788235,780,3,2,unsat,very_high,considering,1
4,1,29215,208,85,224784,241,21,1,very_unsat,little,never_thought,0
...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0,153252,0,23,368403,597,1,6,very_sat,little,actively_looking_into_it,0
19996,1,107126,71,82,237397,609,5,2,very_sat,very_little,no,0
19997,0,78529,0,66,172589,275,0,2,unsat,very_high,considering,1
19998,0,78674,47,41,572406,288,4,2,very_unsat,little,considering,1
19999,0,124697,0,0,845575,808,24,14,unsat,high,actively_looking_into_it,1

**2) x, y 분리**

In [7]:
# Target 설정
target='CHURN'

# 데이터 분리
x=data.drop(target, axis=1)
y=data.loc[:, target]

**3) 가변수화**

In [8]:
# 가변수화 대상: REPORTED_SATISFACTION, REPORTED_USAGE_LEVEL, CONSIDERING_CHANGE_OF_PLAN
dum_cols = ['REPORTED_SATISFACTION', 'REPORTED_USAGE_LEVEL', 'CONSIDERING_CHANGE_OF_PLAN']

# 가변수화
x = pd.get_dummies(x, dum_cols, drop_first=True, dtype=int)

# 확인
x

,COLLEGE,INCOME,OVERAGE,LEFTOVER,HOUSE,HANDSET_PRICE,OVER_15MINS_CALLS_PER_MONTH,AVERAGE_CALL_DURATION,REPORTED_SATISFACTION_sat,REPORTED_SATISFACTION_unsat,REPORTED_SATISFACTION_very_sat,REPORTED_SATISFACTION_very_unsat,REPORTED_USAGE_LEVEL_high,REPORTED_USAGE_LEVEL_little,REPORTED_USAGE_LEVEL_very_high,REPORTED_USAGE_LEVEL_very_little,CONSIDERING_CHANGE_OF_PLAN_considering,CONSIDERING_CHANGE_OF_PLAN_never_thought,CONSIDERING_CHANGE_OF_PLAN_no,CONSIDERING_CHANGE_OF_PLAN_perhaps
0,0,31953,0,6,313378,161,0,4,0,1,0,0,0,1,0,0,0,0,1,0
1,1,36147,0,13,800586,244,0,6,0,1,0,0,0,1,0,0,1,0,0,0
2,1,27273,230,0,305049,201,16,15,0,1,0,0,0,0,0,1,0,0,0,1
3,0,120070,38,33,788235,780,3,2,0,1,0,0,0,0,1,0,1,0,0,0
4,1,29215,208,85,224784,241,21,1,0,0,0,1,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0,153252,0,23,368403,597,1,6,0,0,1,0,0,1,0,0,0,0,0,0
19996,1,107126,71,82,237397,609,5,2,0,0,1,0,0,0,0,1,0,0,1,0
19997,0,78529,0,66,172589,275,0,2,0,1,0,0,0,0,1,0,1,0,0,0
19998,0,78674,47,41,572406,288,4,2,0,0,0,1,0,1,0,0,1,0,0,0
19999,0,124697,0,0,845575,808,24,14,0,1,0,0,1,0,0,0,0,0,0,0

**4) 학습용, 평가용 데이터 분리**

In [9]:
# 모듈 불러오기
from sklearn.model_selection import train_test_split

# 7:3으로 분리
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

**5) 정규화**

In [10]:
# 모듈 불러오기
from sklearn.preprocessing import MinMaxScaler

# 정규화
scaler = MinMaxScaler()
x_train_s = scaler.fit_transform(x_train)
x_test_s = scaler.transform(x_test)

# 4.성능 예측

- k-Fold Cross Validation을 사용해 모델의 성능을 예측합니다.

In [18]:
# 불러오기
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix

In [12]:
# 선언하기
knn_model = KNeighborsClassifier()

In [15]:
# 성능예측
cv_score = cross_val_score(knn_model, x_train_s, y_train, cv=10, scoring='accuracy')

In [16]:
# 결과확인
print(cv_score)
print(cv_score.mean())

[0.60071429 0.59071429 0.61357143 0.59285714 0.57785714 0.58357143
 0.60214286 0.61357143 0.58857143 0.60928571]
0.5972857142857143

# 5.모델 튜닝


- Random Search로 튜닝을 진행합니다.

**1) 모델 튜닝**

In [20]:
# 파라미터 선언
  # n_neighbors: range(3, 21)
param = {'n_neighbors': range(3, 21)}

# Random Search 선언
  # cv=5
  # n_iter=10
  # scoring='accuracy'
model = RandomizedSearchCV(knn_model, param, cv=5, n_iter=10, scoring='accuracy')

In [21]:
# 학습하기
model.fit(x_train_s, y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(),
                   param_distributions={'n_neighbors': range(3, 21)},
                   scoring='accuracy')

**2) 결과 확인**

In [28]:
model.cv_results_

{'mean_fit_time': array([0.00505452, 0.00231495, 0.00267315, 0.00658112, 0.00848961,
        0.00806618, 0.00078177, 0.00509028, 0.00416336, 0.00534124]),
 'std_fit_time': array([0.00337358, 0.0046299 , 0.0039479 , 0.00543704, 0.00715358,
        0.00691666, 0.00156355, 0.00599361, 0.00269057, 0.00670839]),
 'mean_score_time': array([0.14108744, 0.27258601, 0.19578171, 0.37397337, 0.30803533,
        0.21720748, 0.2629415 , 0.46524358, 0.3666934 , 0.22041812]),
 'std_score_time': array([0.00681302, 0.04364854, 0.03958058, 0.13994106, 0.02615489,
        0.01619138, 0.02039534, 0.09501582, 0.04899264, 0.0085335 ]),
 'param_n_neighbors': masked_array(data=[3, 20, 8, 17, 16, 4, 9, 18, 19, 5],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_neighbors': 3},
  {'n_neighbors': 20},
  {'n_neighbors': 8},
  {'n_neighbors': 17},
  {'n_neighbors': 16},
  {'n_neighbors': 4},
  {'n_neighbors': 9},
  {'n_neighbors': 18},
  {'n_neighbors': 19},
  {'n_neighbors': 5}],
 'split0_test_score': array([0.58821429, 0.58321429, 0.59178571, 0.58821429, 0.58464286,
        0.58607143, 0.58607143, 0.5825    , 0.58642857, 0.58571429]),
 'split1_test_score': array([0.59571429, 0.61      , 0.5925    , 0.60678571, 0.6025    ,
        0.59107143, 0.60321429, 0.6075    , 0.60607143, 0.60035714]),
 'split2_test_score': array([0.57107143, 0.59785714, 0.58071429, 0.58035714, 0.58892857,
        0.56678571, 0.57857143, 0.59107143, 0.58964286, 0.57785714]),
 'split3_test_score': array([0.60035714, 0.60178571, 0.60571429, 0.60714286, 0.60892857,
        0.60214286, 0.605     , 0.605     , 0.61107143, 0.60321429]),
 'split4_test_score': array([0.59714286, 0.59571429, 0.6       , 0.59642857, 0.59035714,
        0.58535714, 0.60392857, 0.59285714, 0.60107143, 0.59785714]),
 'mean_test_score': array([0.5905    , 0.59771429, 0.59414286, 0.59578571, 0.59507143,
        0.58628571, 0.59535714, 0.59578571, 0.59885714, 0.593     ]),
 'std_test_score': array([0.01049927, 0.00873826, 0.00844732, 0.01044763, 0.00912051,
        0.01144998, 0.01091946, 0.00926756, 0.00943939, 0.00963783]),
 'rank_test_score': array([ 9,  2,  7,  3,  6, 10,  5,  3,  1,  8])}

In [25]:
# mean_test_score 확인
print(model.cv_results_['mean_test_score'])

[0.5905     0.59771429 0.59414286 0.59578571 0.59507143 0.58628571
 0.59535714 0.59578571 0.59885714 0.593     ]

In [26]:
# 최적 파라미터
print(model.best_params_)

{'n_neighbors': 19}

In [27]:
# 최고 성능
print(model.best_score_)

0.5988571428571429

# 6. 성능 평가

- 학습을 통해 예상한 성능과 실제 평가에 따른 성능은 차이가 있을 수 있습니다.
- 예선전에서 성적이 좋았다고 본선에서도 성적이 좋다고 보장할 수는 없겠지요?

In [29]:
# 예측하기
y_pred = model.predict(x_test_s)

In [31]:
# 평가하기
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[2039 1026]
 [1253 1682]]
              precision    recall  f1-score   support

           0       0.62      0.67      0.64      3065
           1       0.62      0.57      0.60      2935

    accuracy                           0.62      6000
   macro avg       0.62      0.62      0.62      6000
weighted avg       0.62      0.62      0.62      6000